#!/bin/bash
# Sourced by each project's run-services.sh, which sets SHARED_NETWORKS first.
# Manages the project's compose stack; all external traffic goes through the
# shared Traefik (infra/gateway) on :80.
#
# Proxy mode runs a backend service on the host instead of in compose:
# `run <svc>` picks a free port, writes a route file into the gateway's
# watched directory sending the service's API host + path prefix to
# host.docker.internal:<port>, and runs it with its rendered host.env. The
# route goes away when the process exits. Services flagged 1 in proxy.conf
# are left out of `start`/`up` so the container doesn't come back.

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT="$(basename "$PROJECT_DIR")"
FORMATION_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
APPS_DIR="$(cd "$FORMATION_ROOT/.." && pwd)"
cd "$PROJECT_DIR"

COMPOSE_CMD=(docker compose -f "$PROJECT_DIR/docker-compose.yml" --project-directory "$PROJECT_DIR")
ROUTES_DIR="$FORMATION_ROOT/infra/gateway/routes"
# Rendered by shared/tasks/render-services.yml: BACKEND_DIR, API_DOMAINS, SERVICES.
SERVICES_FILE=".services.sh"
PROXY_CONF="proxy.conf"

# Shares the gateway's directory with every project's rendered <project>.yml,
# so proxy route files get a name those never use.
proxy_route_file() {
    echo "$ROUTES_DIR/$PROJECT-proxy-$1.yml"
}

# account-service -> ACCOUNT_SERVICE, its flag in proxy.conf.
proxy_var() {
    local var="${1^^}"
    echo "${var//-/_}"
}

load_services() {
    if [[ ! -f "$SERVICES_FILE" ]]; then
        echo "$SERVICES_FILE not found. Run './run-services.sh render' first." >&2
        exit 1
    fi
    # shellcheck disable=SC1090
    source "./$SERVICES_FILE"
}

require_compose_file() {
    if [[ ! -f docker-compose.yml ]]; then
        echo "docker-compose.yml not found. Run './run-services.sh render' first." >&2
        exit 1
    fi
}

ensure_networks() {
    for net in "${SHARED_NETWORKS[@]}"; do
        docker network inspect "$net" >/dev/null 2>&1 || docker network create "$net" >/dev/null
    done
}

render() {
    local local_mode=localhost
    [[ "${1:-}" == "--local" ]] && local_mode=local
    ansible-playbook playbook.yml -e "local_mode=$local_mode"
}

read_proxied_services() {
    proxied=()
    [[ -f "$PROXY_CONF" ]] || return 0
    # shellcheck disable=SC1090
    source "./$PROXY_CONF"
    local svc var
    for svc in $("${COMPOSE_CMD[@]}" config --services); do
        var="$(proxy_var "$svc")"
        [[ "${!var:-0}" == "1" ]] && proxied+=("$svc")
    done
    return 0
}

# Every project's routes are served by the shared Traefik (infra/gateway), so
# without it nothing answers on :80. Starts it if it isn't already running.
ensure_gateway() {
    if [[ -z "$(docker ps -q \
        --filter label=com.docker.compose.project=gateway \
        --filter label=com.docker.compose.service=traefik)" ]]; then
        echo "Starting the shared gateway (infra/gateway)..."
        "$FORMATION_ROOT/infra/gateway/run-services.sh" up
    fi
}

bring_up() {
    local build_flag="${1:-}"
    require_compose_file
    read_proxied_services
    ensure_networks
    ensure_gateway

    if [[ ${#proxied[@]} -eq 0 ]]; then
        "${COMPOSE_CMD[@]}" up ${build_flag} -d --remove-orphans
        return
    fi

    local dockerized=() svc
    for svc in $("${COMPOSE_CMD[@]}" config --services); do
        [[ " ${proxied[*]} " == *" $svc "* ]] || dockerized+=("$svc")
    done

    echo "Dockerized: ${dockerized[*]}"
    echo "Proxied (host): ${proxied[*]}"
    "${COMPOSE_CMD[@]}" up ${build_flag} -d "${dockerized[@]}"
    # Starting a dependent brings its dependencies up too.
    for svc in "${proxied[@]}"; do
        "${COMPOSE_CMD[@]}" rm -fs "$svc" >/dev/null 2>&1 || true
    done

    echo
    echo "Run each proxied service in its own terminal:"
    for svc in "${proxied[@]}"; do
        echo "  ./run-services.sh run $svc"
    done
}

write_proxy_route() {
    local svc="$1" prefix="$2" port="$3" domain i=0
    mkdir -p "$ROUTES_DIR"
    {
        echo "# Generated by $PROJECT's run-services.sh — proxy route for $svc."
        echo "http:"
        echo "  routers:"
        for domain in "${API_DOMAINS[@]}"; do
            echo "    $PROJECT-$svc-proxy-$((i++)):"
            echo "      rule: \"Host(\`$domain\`) && PathPrefix(\`$prefix\`)\""
            echo "      service: $PROJECT-$svc-proxy"
            echo "      entryPoints: [web]"
            echo "      # Beats the rendered route for the same host + prefix, which"
            echo "      # points at the (stopped) container."
            echo "      priority: 1000"
        done
        echo "  services:"
        echo "    $PROJECT-$svc-proxy:"
        echo "      loadBalancer:"
        echo "        servers:"
        echo "          - url: \"http://host.docker.internal:$port\""
    } > "$(proxy_route_file "$svc")"
}

# Resources publish on a loopback port Docker picks, so `local` addresses carry
# <host-port:[project/]service:port> instead of a number. Prints the host port
# Docker published that container port on, looking in this project unless
# another is named.
resolve_host_port() {
    local ref="$1" project="$PROJECT" svc cport cid published
    if [[ "$ref" == */* ]]; then
        project="${ref%%/*}"
        ref="${ref#*/}"
    fi
    svc="${ref%%:*}"
    cport="${ref#*:}"
    cid="$(docker ps -q \
        --filter "label=com.docker.compose.project=$project" \
        --filter "label=com.docker.compose.service=$svc" | head -n1)"
    if [[ -z "$cid" ]]; then
        echo "$project's $svc isn't running; start it with its './run-services.sh up'." >&2
        return 1
    fi
    published="$(docker port "$cid" "$cport/tcp" 2>/dev/null | head -n1)"
    if [[ -z "$published" ]]; then
        echo "$project's $svc doesn't publish port $cport; add it to its compose.ports." >&2
        return 1
    fi
    echo "${published##*:}"
}

# Prints a host.env with each <host-port:...> replaced by its current port.
resolve_host_env() {
    local file="$1" env token port
    env="$(<"$file")"
    for token in $(grep -o '<host-port:[^>]*>' "$file" | sort -u || true); do
        port="$(resolve_host_port "${token:11:-1}")" || return 1
        env="${env//"$token"/$port}"
    done
    printf '%s\n' "$env"
}

# Every published port of this project's running containers.
show_ports() {
    require_compose_file
    local svc cid
    for svc in $("${COMPOSE_CMD[@]}" config --services); do
        cid="$("${COMPOSE_CMD[@]}" ps -q "$svc" 2>/dev/null || true)"
        [[ -n "$cid" ]] || continue
        docker port "$cid" | sed "s/^/$svc  /"
    done
}

run_on_host() {
    local svc="${1:-}" entry name prefix cmd_dir port route env
    load_services
    for entry in "${SERVICES[@]}"; do
        read -r name prefix cmd_dir <<<"$entry"
        [[ "$name" == "$svc" ]] && break
        name=""
    done
    if [[ -z "$name" ]]; then
        echo "Usage: $0 run <service>, one of:" >&2
        for entry in "${SERVICES[@]}"; do echo "  ${entry%% *}" >&2; done
        exit 1
    fi
    if [[ ! -f "backend/$svc/host.env" ]]; then
        echo "backend/$svc/host.env not found. Run './run-services.sh render' first." >&2
        exit 1
    fi

    # Before stopping anything, so an unpublished resource fails cleanly.
    env="$(resolve_host_env "backend/$svc/host.env")"

    if [[ -f docker-compose.yml ]]; then
        "${COMPOSE_CMD[@]}" rm -fs "$svc" >/dev/null 2>&1 || true
    fi
    port="$(python3 -c 'import socket;s=socket.socket();s.bind(("",0));print(s.getsockname()[1]);s.close()')"
    write_proxy_route "$svc" "$prefix" "$port"
    # Expanded now: the trap runs after this function's locals are gone.
    route="$(proxy_route_file "$svc")"
    trap "rm -f '$route'; echo '[proxy] $svc route removed'" EXIT
    echo "[proxy] $svc on host port $port, routed from ${API_DOMAINS[*]} $prefix"

    (
        set -a
        # shellcheck disable=SC1090
        source <(printf '%s\n' "$env")
        set +a
        PORT="$port" go -C "$APPS_DIR/$BACKEND_DIR" run "./$cmd_dir"
    )
}

teardown_proxy_routes() {
    rm -f "$ROUTES_DIR/$PROJECT-proxy-"*.yml
}

edit_proxy_conf() {
    if [[ ! -f "$PROXY_CONF" ]]; then
        load_services
        {
            echo "# Set a service to 1 to run it on the host (proxy mode):"
            echo "# 'start'/'up' leave flagged services out of docker-compose,"
            echo "# and './run-services.sh run <svc>' runs one on the host."
            echo
            local entry
            for entry in "${SERVICES[@]}"; do
                echo "$(proxy_var "${entry%% *}")=0"
            done
        } > "$PROXY_CONF"
        echo "Created $PROXY_CONF."
    fi
    "${EDITOR:-vi}" "$PROXY_CONF"
}

proxy_status() {
    local f found=0
    for f in "$ROUTES_DIR/$PROJECT-proxy-"*.yml; do
        [[ -f "$f" ]] || continue
        found=1
        f="$(basename "$f" .yml)"
        echo "on host: ${f#"$PROJECT-proxy-"}"
    done
    [[ $found -eq 1 ]] || echo "No services running on the host."
}

usage() {
    cat <<EOF
Usage: $0 <command>

  render [--local]  Generate .env files, docker-compose.yml and Traefik routes
                    via ansible-playbook. Rendered URLs use the .localhost
                    domains by default, the server domains (*.home) with --local.
  start             render, then build + up -d (proxy.conf flagged services excluded)
  up                up -d, no rebuild               (proxy.conf flagged services excluded)
  kill              down --remove-orphans, and clear proxy routes
  delete            purge containers, images, volumes, and clear proxy routes
  proxy             Seed/edit proxy.conf — flag a service as 1 to keep it out of compose
  run <service>     Run a service on the host, routed through the gateway until it exits
  status            Show which services are running on the host
  ports             Show the loopback ports Docker published this project's containers on
EOF
}

case "${1:-}" in
    render) render "${2:-}" ;;
    start)
        render
        bring_up --build
        ;;
    up) bring_up ;;
    kill)
        teardown_proxy_routes
        "${COMPOSE_CMD[@]}" down --remove-orphans
        ;;
    delete)
        teardown_proxy_routes
        "${COMPOSE_CMD[@]}" down --remove-orphans --rmi all --volumes
        ;;
    proxy)  edit_proxy_conf ;;
    run)    run_on_host "${2:-}" ;;
    status) proxy_status ;;
    ports)  show_ports ;;
    *)
        usage
        exit 1
        ;;
esac
